<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<link type="text/css" href="style/main.css"  rel="stylesheet"/>
<link href="style/reset.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="js/jquery-1.8.3.js"></script>
<script type="text/javascript" src="js/main.js"></script>
<title>胜诚租车</title>
</head>

<body>
<div class="header">
      <div class="topBar overH">
       <div class="comWidth">
         <div class="welcome fl"><p></p></div>
          <div class="followUS overH fr">
           <span class="fl">关注我们：</span>
  <!-- JiaThis Button BEGIN -->
     <div class="jiathis_style_24x24" style="margin-top:5px;">
	<a class="jiathis_button_tsina"></a><a class="jiathis_button_weixin"></a><a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a><a class="jiathis_counter_style"></a>
    </div>
     <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
       <!-- JiaThis Button END -->
         </div> 
          </div>
         </div>
         
        <div class="comWidth bottomBar overH">
          <div class="logo fl"><a href="#"><img src="images/shengchengLogo.gif" alt="logo" /></a></div>
            <ul class="nav fr">
               <li><a href="#" >首页</a></li>
                <li><a href="#">汽车类型</a></li> 
                 <li><a href="#">服务内容</a></li> 
                <li><a href="#">租还流程</a></li>
               <li><a href="#">关于胜诚</a></li>   
               </ul> 
         </div>  
   </div>
  <!------ header结束---- -->
  <div class="headAdv">
    <img src="images/headAdv.gif" alt="广告" />
     </div>
    <!-- advBanner结束-->
  <div class="feature">
  <div class="comWidth">
    <ul class="overH">
      <li><img src="images/feature_1.gif" alt="特色" /></li>
        <li><img src="images/feature_2.gif" alt="特色" /></li>
         <li><img src="images/feature_3.gif" alt="特色" /></li>
          <li class="noBoder"><img src="images/feature_4.gif" alt="特色" /></li>
      </ul>
    </div>  
    </div>  
 <!-- feature结束  -->
 <div class="content comWidth">
    <div class="con_title overH"><h2 class="fl">热门车型</h2><a href="#" class="fr">更多</a></div>
    <table class="car_showcase">
      <tr class="overH">
      <tr><td><div class="fill"></div></td></tr>
        <td>
        <div class="td_wrap" style="margin-left:1px;">
         <a href="#"><img src="images/carType_1.gif" alt="热门车型" /></a>
          <div class="configuration overH">
            <dl class="fl"><dt>荣威550</dt><dd>三厢 5座 自动</dd></dl>
             <i class="fr">60/天</i>
              </div>
            </div>  
            </td>
         <td>
         <div class="td_wrap"> 
           <a href="#"><img src="images/carType_2.gif" alt="热门车型" /></a>
          <div class="configuration overH">
            <dl class="fl"><dt>MGGT</dt><dd>三厢 5座 自动</dd></dl>
             <i class="fr">60/天</i>
              </div>
            </div>  
            </td>
          <td>
           <div class="td_wrap">
           <a href="#"><img src="images/carType_3.gif" alt="热门车型" /></a>
          <div class="configuration overH">
            <dl class="fl"><dt>本田CRV</dt><dd>其他 5座 自动</dd></dl>
             <i class="fr">60/天</i>
              </div>
            </div>  
            </td>
           <td>
           <div class="td_wrap"> 
            <a href="#"><img src="images/carType_4.gif" alt="热门车型" /></a>
          <div class="configuration overH">
            <dl class="fl"><dt>本田飞度</dt><dd>两厢 5座 自动</dd></dl>
             <i class="fr">60/天</i>
              </div>
            </div>  
             </td>
         </tr>
       <tr class="overH">
      <tr><td><div class="fill"></div></td></tr>
        <td>
        <div class="td_wrap" style="margin-left:1px;">
         <a href="#"><img src="images/carType_5.gif" alt="热门车型" /></a>
          <div class="configuration overH">
            <dl class="fl"><dt>标致207</dt><dd>两厢 5座 自动</dd></dl>
             <i class="fr">60/天</i>
              </div>
            </div>  
            </td>
         <td>
         <div class="td_wrap"> 
           <a href="#"><img src="images/carType_6.gif" alt="热门车型" /></a>
          <div class="configuration overH">
            <dl class="fl"><dt>标致3008</dt><dd>SUV 5座 自动</dd></dl>
             <i class="fr">60/天</i>
              </div>
            </div>  
            </td>
          <td>
           <div class="td_wrap">
           <a href="#"><img src="images/carType_7.gif" alt="热门车型" /></a>
          <div class="configuration overH">
            <dl class="fl"><dt>标致307</dt><dd>两厢 5座 自动</dd></dl>
             <i class="fr">60/天</i>
              </div>
            </div>  
            </td>
           <td>
           <div class="td_wrap"> 
            <a href="#"><img src="images/carType_8.gif" alt="热门车型" /></a>
          <div class="configuration overH">
            <dl class="fl"><dt>别克GL3</dt><dd>其他 7座 自动</dd></dl>
             <i class="fr">60/天</i>
              </div>
            </div>  
             </td>
         </tr>
       </table>
    <div class="epecial_offer overH">
       <div class="fl">
           <ul class="overH">
             <li style="background:#1FAEA5;"><a href="#">自驾租车</a></li>
               <li style="background:#01A300;"><a href="#">代驾租车</a></li>
                 <li style="background:#FFC40E;"><a href="#">长期租车</a></li>
                  <li style="background:#525252;"><a href="#">团购租车</a></li>
                 <li style="background:#A000A8;"><a href="#">优惠信息</a></li>
                <li style="background:#2B5796;"><a href="#">租车问答</a></li>
              </ul>
           </div>
        <div class="fr discount">
           <h2>特别套餐<i>（低至6折）</i></h2>
           <div class="rent_period overH"><img src="images/weklyRent.gif" alt="套餐时间" /><img src="images/weeklyRentSe.gif" alt="套餐时间" /><img src="images/monthlyRent.gif" alt="套餐时间" /></div>  
           <p>周租、月租套餐附加增值服务、GPS导航、不计免赔服务、儿童座椅、7天价封顶。</p>
           </div>
       </div>   
     <div class="steps">
      <img src="images/steps.gif" alt="步骤" />
        </div> 
     <div class="detail_menu overH">
        <span class="fl detail_menu_special">
          <h4>租车预定说明</h4>
           <ul>
             <li><a href="#">服务时间</a></li>
              <li><a href="#">待车情况</a></li>
               <li><a href="#">服务预定</a></li>
                <li><a href="#">短期产品</a></li>
                 <li><a href="#">租车资格</a></li>
                  <li><a href="#">取还车说明</a></li>
             </ul>
          </span>
         <span class="fl">
           <h4>会员管理</h4>
           <ul>
             <li><a href="#">会员章程</a></li>
              <li><a href="#">会员细则</a></li>
               <li><a href="#">定级积分</a></li>
             </ul>
            </span>
          <span class="fl">
             <h4>紧急事务处理</h4>
           <ul>
             <li><a href="#">保险责任</a></li>
              <li><a href="#">理赔说明</a></li>
               <li><a href="#">事故处理</a></li>
                <li><a href="#">救援及备用车</a></li>
             </ul>
              </span>
           <span class="fl">
              <h4>租车费用及结算</h4>
           <ul>
             <li><a href="#">价格说明</a></li>
              <li><a href="#">结算流程</a></li>
               <li><a href="#">储值卡</a></li>
             </ul>
               </span>
            <span class="fl" style="padding-left:3px;">
              <h4>帮助中心</h4>
           <ul>
             <li><a href="#">新手上路</a></li>
              <li><a href="#">常见问题</a></li>
               <li><a href="#">服务规则</a></li>
                <li><a href="#">违章查询</a></li>
             </ul>
               </span>
        </div> 
      <div class="carBrand"><a href="#" class="fr"></a></div> 
       </div>
  </div>
 <!-- content结束 -->
 
 <!-- ----------右边客服在线浮动框 ----------------->
    <div class="talk_online overH" id="talk_online">
    <a rel="nofollow" href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes" title="" target="_blank" class="online"></a>
      <img src="images/connectionOnline.gif" alt=""/>
     </div> 
 
  <div class="footer">
     <div class="footer_menu">
       <div class="comWidth f_menu-padding">
          <dl>
             <dt><img src="images/footerimags_1.gif" alt="底部菜单" /></dt>
              <dd><a href="#">关于胜诚</a></dd>
                <dd><a href="#">胜诚记事</a></dd> 
                <dd><a href="#">胜诚荣誉</a></dd> 
             </dl>
           <dl>
             <dt><img src="images/footerimags_2.gif" alt="底部菜单" /></dt>
              <dd><a href="#">租车协议</a></dd>
                <dd><a href="#">相关条例</a></dd> 
                <dd><a href="#">相关责任</a></dd> 
                <dd><a href="#">相关条款</a></dd> 
             </dl>
           <dl>
             <dt><img src="images/footerimags_3.gif" alt="底部菜单" /></dt>
              <dd><a href="#">如何租车</a></dd>
                <dd><a href="#">如何还车</a></dd> 
                <dd><a href="#">紧急事务处理</a></dd> 
             </dl>
           <dl>
             <dt><img src="images/footerimags_4.gif" alt="底部菜单" /></dt>
              <dd><a href="#">如何加盟</a></dd>
                <dd><a href="#">合作方式</a></dd> 
                <dd><a href="#">联系我们</a></dd> 
             </dl>
           <dl>
             <dt><img src="images/footerimags_5.gif" alt="底部菜单" /></dt>
               <!-----注意：到http://bizapp.qq.com/webpres.htm添加企业QQ号和网址----------------> 
                <dd><img  style="CURSOR: pointer" onclick="javascript:window.open('http://b.qq.com/webc.htm?new=0&sid=99112233&o=shengcheng.com&q=7', '_blank', 'height=502, width=644,toolbar=no,scrollbars=no,menubar=no,status=no');"  border="0" SRC=http://wpa.qq.com/pa?p=1:99112233:1 alt="点击这里给我发消息"></dd> 
                <dd>工作时间:08:30-18:00</dd> 
                <dd>邮箱：shengchengqiche</dd> 
             </dl>
           </div>         
        </div>
     <div class="copyRight">
         <p class="comWidth">CopyRight&copy;2014 &nbsp;&nbsp;&nbsp;&nbsp;深圳胜诚汽车租赁有限公司&nbsp;&nbsp;&nbsp; &nbsp;粤ICP备XXXXXXXXX号</p>
        </div>
    </div>
</body>
</html>
