<script type="text/javascript">
    Ext.onReady(function () {
        var win = Ext.create('Ext.window.Window', {
            title: '示例窗口',
            height: 200,
            width: 400,
            minimizable: true,
            maximizable: true,
            collapsible: true,
            modal: true,
            draggable: false,
            resizable: false,
            tbar: [
                { xtype: "button", text: "新增", handler: function () { Ext.MessageBox.alert("提示", "新增按钮点击"); } },
                { xtype: "button", text: "编辑", handler: function () { Ext.MessageBox.alert("提示", "编辑按钮点击"); } }
            ],
            buttons: [
                { xtype: "button", text: "确定" },
                { xtype: "button", text: "取消",handler:function(){win.close(); } },
            ],
            html: "<div style='width:100%;height:100%;background-color:#fff;'>窗口内容</div>"
        });
        win.show();
    });
</script>